name: UBans
main: Hayamajin\UBans
authors: [Hayamajin,XxawarenessxX]
version: 5.0.0
api: [3.0.0,3.8.0,4.0.0]
load: STARTUP
description: 様々な機能を備えた荒らし対策プラグインです
commands:
 uban:
  description: プレイヤーをUBan(名前、IPアドレス、ホスト、クライアントID、ユニークID、ローユニークIDの同時Ban)します。
  permission: op
 unuban:
  description: UBanを解除します
  permission: op
 warn:
  description: 指定したプレイヤーを危険人物に認定します(warn)
  permission: op
 unwarn:
  description: warnを解除します
  permission: op
 ubans:
  description: UBanのコマンドが分かります
  usage:
 uban_txt:
  description: テキストでUBanします
  permission: op
  usage:

